web:
  #添加外部静态资源配置
  upload-path: G://upload/img/
  #当前项目的url
  upload:
    img-path: http://localhost:${server.port}
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/,file:${web.upload-path}
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  #mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.life.community.mapper
  mapper-locations: classpath:mapper/*.xml

  #使用github账号登录支持
github:
  client_id: #github的client_id
  client_secret: #github的client_secret
  redirect_uri: #github的redirect_uri